/**
 * Forrit: Reiknivel, útlitshluti. Þessi klasi tengir takka reiknivélarinnar 
 * við virkni hennar, ásamt því að bæta inn aðferðum til að auðvelda notenda
 * notkun á viðmótinu s.s. að stroka allt út og byrja upp á nýtt ef ýtt er á 
 * tölu á eftir "=" merki.
 * 
 * @author Jónas G. Sigurðsson
 *         jgs7@hi.is
 */
package is.hi.reiknivel.utlit;

/* Importa gefna klasanum Reiknivel og klasanum 
*  JButton til að geta unnið með grid layout
*/
import is.hi.reiknivel.vinnsla.Reiknivel;
import javax.swing.JButton;

public class Utlit extends javax.swing.JFrame {

    // Bý til breytuna myReiknivel, til að geta vísað í aðferðir í gefna klasanum.
    private final Reiknivel myReiknivel;

    // Bý til breytuna samaSem til að vita hvort að ýtt hafi verið á =.
    boolean samaSem = false;

    /* Bý til JButton, líkt og í GridLayoutSynidæmi til að geta 
    *  unnið með alla töluhnappana í sama atburðarhandler
    */
    private final JButton[] REITIR;

    public Utlit() {
        initComponents();

        // Tengi breytuna myReiknivel við klasan Reiknivel.
        myReiknivel = new Reiknivel();

        // Tengi breytuna JButton við töluhnappana.
        REITIR = new JButton[]{j1, j2, j3, j4, j5, j6, j7, j8, j9, j0};
        for (int j = 0; j < 10; j++) {
            REITIR[j].setName(String.valueOf(j + 1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        j1 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        jHreinsa = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        jJafntOg = new javax.swing.JButton();
        jUtkoma = new javax.swing.JTextField();
        jPlus = new javax.swing.JButton();
        jMinus = new javax.swing.JButton();
        jMargfoldun = new javax.swing.JButton();
        jDeiling = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 7, 7));

        j1.setText("1");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j1);

        j2.setText("2");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j2);

        j3.setText("3");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j3);

        j4.setText("4");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j4);

        j5.setText("5");
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j5);

        j6.setText("6");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j6);

        j7.setText("7");
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j7);

        j8.setText("8");
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j8);

        j9.setText("9");
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j9);

        jHreinsa.setText("ac");
        jHreinsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHreinsaActionPerformed(evt);
            }
        });
        jPanel1.add(jHreinsa);

        j0.setText("0");
        j0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalaActionPerformed(evt);
            }
        });
        jPanel1.add(j0);

        jJafntOg.setText("=");
        jJafntOg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJafntOgActionPerformed(evt);
            }
        });
        jPanel1.add(jJafntOg);

        jPlus.setText("+");
        jPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlusActionPerformed(evt);
            }
        });

        jMinus.setText("-");
        jMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinusActionPerformed(evt);
            }
        });

        jMargfoldun.setText("*");
        jMargfoldun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMargfoldunActionPerformed(evt);
            }
        });

        jDeiling.setText("/");
        jDeiling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeilingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUtkoma)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMargfoldun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDeiling, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jUtkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMargfoldun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDeiling, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Atburðarhandler fyrir öll klikk á tölur
    private void jTalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTalaActionPerformed
        // Finnum út hvaða hnapp var ýtt á
        JButton nyrReitur = (JButton) evt.getSource();

        /* Finnum út hvort að ýtt hafi verið á =, ef svo er 
        *  þá núllstillir reiknivélin sig og þurkar út úr glugganum
        */
        if (samaSem == true) {
            myReiknivel.nullStilla();
            samaSem = false;
            jUtkoma.setText(" ");
        }
        // Setur töluna sem ýtt var á inn í gluggann
        String Enternumber = jUtkoma.getText() + nyrReitur.getText();
        jUtkoma.setText(Enternumber);
        /* Löng if setning, fann ekki út hvernig þetta hefði átt að vera 
        *  öðruvísi. En hún skoðar hvaða tölu var ýtt á og passar að færa til 
        *  um sæti.
        */
        if (nyrReitur.getText() == "1") {
            myReiknivel.setTala(1);
        } else if (nyrReitur.getText() == "2") {
            myReiknivel.setTala(2);
        } else if (nyrReitur.getText() == "3") {
            myReiknivel.setTala(3);
        } else if (nyrReitur.getText() == "4") {
            myReiknivel.setTala(4);
        } else if (nyrReitur.getText() == "5") {
            myReiknivel.setTala(5);
        } else if (nyrReitur.getText() == "6") {
            myReiknivel.setTala(6);
        } else if (nyrReitur.getText() == "7") {
            myReiknivel.setTala(7);
        } else if (nyrReitur.getText() == "8") {
            myReiknivel.setTala(8);
        } else if (nyrReitur.getText() == "9") {
            myReiknivel.setTala(9);
        } else if (nyrReitur.getText() == "0") {
            myReiknivel.setTala(0);
        }
    }//GEN-LAST:event_jTalaActionPerformed

    // Atburðarhandler fyrir hreinsunarhnappinn
    private void jHreinsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHreinsaActionPerformed
        //Núllstillir reiknivélina og hreinsar gluggann
        myReiknivel.nullStilla();
        jUtkoma.setText("");
    }//GEN-LAST:event_jHreinsaActionPerformed

    // Atburðarhandler fyrir sama sem hnappinn
    private void jJafntOgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJafntOgActionPerformed
        /* Setur virkjan sem "=" og skoðar hvort að það hafi verið ýtt á 
        *  hann áður, ef svo er þá núllstillir vélin sig og hreinsar gluggan
        */
        int villa = myReiknivel.setVirki('=');

        if (villa == 0) {
            String Enternumber = jUtkoma.getText() + jJafntOg.getText();
            jUtkoma.setText(Enternumber + myReiknivel.getUtkoma());
            samaSem = true;
        } else if (villa == 2) {
            jUtkoma.setText(" ");
            samaSem = false;
        } else {
            myReiknivel.nullStilla();
            samaSem = false;
        }
    }//GEN-LAST:event_jJafntOgActionPerformed

    // Atburðarhandler fyrir samlagningarhnappinn
    private void jPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlusActionPerformed
        /* Byrjar á að skoða hvort ýtt hafi verið á "=", ef svo er þá 
        *  hreinsar vélin og núllstillir sig.
        *  Setur virkjan sem "+" og bætir honum við á skjáinn, gerir 
        *  ekkert ef að síðast var ýtt á virkja
        */
        if (samaSem == true) {
            myReiknivel.nullStilla();
            jUtkoma.setText(" ");
        } else {
            int villa = myReiknivel.setVirki('+');
            if (villa == 0) {
                String Enternumber = jUtkoma.getText() + jPlus.getText();
                jUtkoma.setText(Enternumber);
            }
        }
    }//GEN-LAST:event_jPlusActionPerformed

    // Atburðarhandler fyrir frádráttarhnappinn
    private void jMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinusActionPerformed
        /* Byrjar á að skoða hvort ýtt hafi verið á "=", ef svo er þá 
        *  hreinsar vélin og núllstillir sig.
        *  Setur virkjan sem "-" og bætir honum við á skjáinn, gerir 
        *  ekkert ef að síðast var ýtt á virkja
        */
        if (samaSem == true) {
            myReiknivel.nullStilla();
            jUtkoma.setText(" ");
        } else {
            int villa = myReiknivel.setVirki('-');
            if (villa == 0) {
                String Enternumber = jUtkoma.getText() + jMinus.getText();
                jUtkoma.setText(Enternumber);
            }
        }
    }//GEN-LAST:event_jMinusActionPerformed

    // Atburðarhandler fyrir margföldunarhnappinn
    private void jMargfoldunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMargfoldunActionPerformed
        /* Byrjar á að skoða hvort ýtt hafi verið á "=", ef svo er þá 
        *  hreinsar vélin og núllstillir sig.
        *  Setur virkjan sem "*" og bætir honum við á skjáinn, gerir 
        *  ekkert ef að síðast var ýtt á virkja
        */
        if (samaSem == true) {
            myReiknivel.nullStilla();
            jUtkoma.setText(" ");
        } else {
            int villa = myReiknivel.setVirki('*');
            if (villa == 0) {
                String Enternumber = jUtkoma.getText() + jMargfoldun.getText();
                jUtkoma.setText(Enternumber);
            }
        }
    }//GEN-LAST:event_jMargfoldunActionPerformed

    // Atburðarhandler fyrir deilingarhnappinn
    private void jDeilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeilingActionPerformed
        /* Byrjar á að skoða hvort ýtt hafi verið á "=", ef svo er þá 
        *  hreinsar vélin og núllstillir sig.
        *  Setur virkjan sem "/" og bætir honum við á skjáinn, gerir 
        *  ekkert ef að síðast var ýtt á virkja
        */
        if (samaSem == true) {
            myReiknivel.nullStilla();
            jUtkoma.setText(" ");
        } else {
            int villa = myReiknivel.setVirki('/');
            if (villa == 0) {
                String Enternumber = jUtkoma.getText() + jDeiling.getText();
                jUtkoma.setText(Enternumber);
            }
        }
    }//GEN-LAST:event_jDeilingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utlit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utlit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jDeiling;
    private javax.swing.JButton jHreinsa;
    private javax.swing.JButton jJafntOg;
    private javax.swing.JButton jMargfoldun;
    private javax.swing.JButton jMinus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPlus;
    private javax.swing.JTextField jUtkoma;
    // End of variables declaration//GEN-END:variables
}
